import React, { useState } from 'react';
import { supabase } from '../lib/supabase';

export default function SquadIntelligenceCard({ squadId, squadName, stats, strokeData, trend, type = 'squad' }) {
  const [loading, setLoading] = useState(false);
  const [insight, setInsight] = useState(null);
  const [error, setError] = useState(null);
  const [history, setHistory] = useState([]);
  const [showHistory, setShowHistory] = useState(false);

  const hasAutoGenerated = React.useRef({});

  React.useEffect(() => {
    hasAutoGenerated.current = {};
    fetchLatestInsight();
  }, [squadId]);

  const fetchLatestInsight = async () => {
    try {
      // Filter on `type` in BOTH branches. Filtering only by squad_id meant a
      // TalentIntelligenceCard report (type:'talent') written against the same
      // squad could be loaded here, and its different shape then crashed the
      // render below.
      let query = supabase.from('ai_reports')
        .select('*')
        .eq('type', type)
        .order('created_at', { ascending: false });
      if (squadId) query = query.eq('squad_id', squadId);

      const { data, error } = await query.limit(10);
      if (error) throw error;
      
      if (data && data.length > 0) {
        setInsight(data[0].content);
        setHistory(data);
      } else {
        const key = squadId || 'club';
        if (!hasAutoGenerated.current[key]) {
          hasAutoGenerated.current[key] = true;
          generateInsight();
        }
      }
    } catch (err) {
      console.error("Error fetching latest insight:", err);
    }
  };

  const generateInsight = async () => {
    setLoading(true);
    setError(null);
    try {
      const { data: { session: authSession } } = await supabase.auth.getSession();
      const res = await fetch('/api/ai/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${authSession?.access_token}` },
        body: JSON.stringify({
          squadId: squadId || 'club',
          type: type,
          squadName,
          stats,
          strokeData,
          trend
        })
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setInsight(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (!insight && !loading) {
    return (
      <div className="glass-card animate-fade-in no-print" style={{ textAlign: 'center', padding: '3rem' }}>
        <div className="section-title" style={{ justifyContent: 'center' }}>CoachesEye Insights Lab</div>
        <h3 style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--accent-cyan)', textTransform: 'uppercase', letterSpacing: '0.1em', paddingBottom: '0.75rem', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: '1.5rem', marginTop: '1rem' }}>{type === 'club' ? 'Club' : 'Squad'} Performance Audit</h3>
        <p style={{ fontSize: '0.85rem', opacity: 0.8, lineHeight: 1.6, maxWidth: '500px', margin: '0 auto 2rem' }}>
          Synthesizing aggregate data into a strategic technical roadmap for the entire {type === 'club' ? 'club' : 'squad'}.
        </p>
        <button className="btn-premium-action" onClick={generateInsight} style={{ margin: '0 auto' }}>
          <span>✨</span> Run Squad Analysis
        </button>
        {error && <p style={{ color: 'var(--accent-rose)', marginTop: '1rem', fontSize: '0.8rem' }}>{error}</p>}
      </div>
    );
  }
  if (loading) {
    return (
      <div className="glass-card animate-fade-in no-print" style={{ padding: '4rem', textAlign: 'center' }}>
        <div className="loading-spinner" style={{ marginBottom: '1.5rem' }}>✨</div>
        <p className="animate-pulse" style={{ fontSize: '1.1rem', fontWeight: 600 }}>Synthesizing Technical Audit...</p>
        <p style={{ fontSize: '0.7rem', opacity: 0.5, marginTop: '10px' }}>Analyzing Aggregate Velocity & Squad Consistency</p>
      </div>
    );
  }

  // A report that doesn't carry the expected object shape (older schema, partial
  // write, truncated model response) used to take the whole squad page down
  // rather than degrading this one panel.
  if (!insight || typeof insight.summary !== 'object' || insight.summary === null) {
    return (
      <div className="glass-card animate-fade-in no-print" style={{ padding: '3rem', textAlign: 'center' }}>
        <div className="section-title" style={{ justifyContent: 'center', marginBottom: '1rem' }}>COACHESEYE INTELLIGENCE LAB</div>
        <p style={{ fontSize: '0.9rem', opacity: 0.7, marginBottom: '1.5rem' }}>
          This squad&apos;s stored audit can&apos;t be displayed — it was saved in an older or incomplete format.
        </p>
        <button className="btn-premium-intel mini" onClick={generateInsight}>GENERATE A NEW AUDIT</button>
      </div>
    );
  }

  const swot = insight.summary.swot || {};

  return (
    <div className="glass-card animate-fade-in" style={{ position: 'relative', overflow: 'visible', padding: '3.5rem' }}>
      <div className="flex justify-between items-center mb-12">
        <div className="flex items-center gap-6">
          <div className="section-title">COACHESEYE INTELLIGENCE LAB</div>
          {insight.flag && (
            <div className={`status-badge ${insight.risk_level === 'high' ? 'critical' : (insight.risk_level === 'medium' ? 'attention' : 'success')}`} style={{ fontSize: '0.7rem', padding: '6px 14px', borderRadius: '8px' }}>
              {insight.flag.toUpperCase()}
            </div>
          )}
        </div>
        <div className="flex items-center gap-4 no-print">
          <button className="btn-premium-intel mini" onClick={generateInsight}>REFRESH AUDIT</button>
        </div>
      </div>

      <div className="mb-14">
        <h3 style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--accent-cyan)', textTransform: 'uppercase', letterSpacing: '0.1em', paddingBottom: '0.75rem', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: '1.5rem', marginTop: '1rem' }}>{insight.headline}</h3>
        
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 mb-12">
          <div className="lg:col-span-2">
             <div className="section-title" style={{ fontSize: '0.65rem', marginBottom: '1.5rem', opacity: 0.5 }}>GROUP PERFORMANCE PROFILE</div>
             <p style={{ fontSize: '0.85rem', opacity: 0.8, lineHeight: 1.6, marginBottom: '2rem' }}>{insight.summary.assessment || '—'}</p>

             <div className="section-title" style={{ fontSize: '0.65rem', marginBottom: '1.5rem', opacity: 0.5 }}>TECHNICAL REVIEW</div>
             <div style={{ fontSize: '0.85rem', opacity: 0.8, lineHeight: 1.6 }}>
                {String(insight.analysis || '').split('\n').filter(Boolean).map((p, i) => <p key={i} style={{ marginBottom: '1.2rem' }}>{p}</p>)}
             </div>
          </div>

          <div className="bg-white/[0.03] border border-white/10 rounded-3xl p-8 backdrop-blur-md">
            <div className="section-title" style={{ fontSize: '0.65rem', marginBottom: '2rem', justifyContent: 'center' }}>STRATEGIC SWOT</div>
            <div className="space-y-8">
              <div>
                <div style={{ fontSize: '0.7rem', color: '#10b981', fontWeight: 950, textTransform: 'uppercase', marginBottom: 8, letterSpacing: '0.1em' }}>Strengths</div>
                <div style={{ fontSize: '0.9rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.5 }}>{swot.strengths || '—'}</div>
              </div>
              <div>
                <div style={{ fontSize: '0.7rem', color: 'var(--accent-rose)', fontWeight: 950, textTransform: 'uppercase', marginBottom: 8, letterSpacing: '0.1em' }}>Weaknesses</div>
                <div style={{ fontSize: '0.9rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.5 }}>{swot.weaknesses || '—'}</div>
              </div>
              <div>
                <div style={{ fontSize: '0.7rem', color: 'var(--accent-cyan)', fontWeight: 950, textTransform: 'uppercase', marginBottom: 8, letterSpacing: '0.1em' }}>Opportunities</div>
                <div style={{ fontSize: '0.9rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.5 }}>{swot.opportunities || '—'}</div>
              </div>
              <div>
                <div style={{ fontSize: '0.7rem', color: '#f59e0b', fontWeight: 950, textTransform: 'uppercase', marginBottom: 8, letterSpacing: '0.1em' }}>Threats</div>
                <div style={{ fontSize: '0.9rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.5 }}>{swot.threats || '—'}</div>
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 pt-12 border-t border-white/10">
          <div>
            <div className="section-title" style={{ fontSize: '0.65rem' }}>SEASON OUTLOOK</div>
            <div style={{ padding: '2rem', background: 'linear-gradient(135deg, rgba(0, 212, 255, 0.08), transparent)', borderRadius: '24px', border: '1px solid rgba(0, 212, 255, 0.15)' }}>
              <p style={{ fontSize: '0.85rem', opacity: 0.8, lineHeight: 1.6, fontStyle: 'italic', margin: 0 }}>
                "{insight.foresight}"
              </p>
            </div>
          </div>

          <div>
            <div className="section-title" style={{ fontSize: '0.65rem' }}>SQUAD TRAINING FOCUS</div>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'grid', gap: '1rem' }}>
              {(insight.recommendations || []).map((rec, i) => (
                <li key={i} style={{ fontSize: '0.85rem', opacity: 0.8, lineHeight: 1.6, display: 'flex', gap: '16px', alignItems: 'flex-start' }}>
                  <div style={{ minWidth: '8px', height: '8px', borderRadius: '50%', background: 'var(--accent-cyan)', marginTop: '8px', boxShadow: '0 0 10px var(--accent-cyan)' }}></div>
                  <span style={{ color: 'rgba(255,255,255,0.7)', fontWeight: 500 }}>{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      <style jsx>{`
        .loading-spinner {
          font-size: 3rem;
          animation: spin 2s linear infinite;
          display: inline-block;
        }
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
        .animate-pulse {
          animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
        }
        .animate-fade-in {
          animation: fadeIn 0.4s ease-out;
        }
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  );
}
